
services:
  api:
    build: ./api
    restart: always
    depends_on:
      db:
        condition: service_started
        restart: true
    environment:
      DB_HOST: ${DB_HOST} 
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_DIALECT: ${DB_DIALECT}
      NODE_ENV: "development"
    ports:
      - "3000:3000"

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"

  
  web:
    build: ./web
    ports:
      - 4200:4200
    volumes:
      - ./web:/project
      - /project/node_modules
