networks:
  default:
    ipam:
      config:
        - subnet: 172.18.0.0/16


services:
  api:
    container_name: api
    build: ./api
    restart: always
    depends_on:
      db:
        condition: service_started
        restart: true
    environment:
      DB_HOST: ${DB_HOST} 
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD} 
      DB_DATABASE: ${DB_DATABASE}
      DB_DIALECT: ${DB_DIALECT}
      NODE_ENV: "development"
    networks:
      default:
        ipv4_address: 172.18.0.4
    ports:
      - "3000:3000"
    volumes:
      - "./api:/usr/src/app"
    command: npm run api:start

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      default:
        ipv4_address: 172.18.0.3
    ports:
      - "3306:3306"
    volumes:
      - "./db/custom.cnf:/etc/mysql/conf.d/custom.cnf"


  openresty:
    build: ./nginx
    container_name: server
    environment:
      DB_HOST: ${DB_HOST} 
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_DIALECT: ${DB_DIALECT}
    networks:
      default:
        ipv4_address: 172.18.0.2
    ports:
      - "80:80"
      - "443:443"
    volumes:
     - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
     - "./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
     - "./nginx/lua:/home/openresty/lua"
     - "./nginx/lua/lib:/usr/local/openresty/site/lualib/lib"

  php:
    container_name: php
    build: ./web
    extra_hosts:
    - "host.docker.internal:host-gateway"
    networks:
      default:
        ipv4_address: 172.18.0.5
    ports:
    - "8080:80"  
    - "8443:443"
    volumes:
    - ./web/www:/var/www/html

