FROM node:22-alpine

WORKDIR /usr/src/app

COPY . /usr/src/app

EXPOSE 3000

RUN npm install

RUN npx sequelize-cli db:create

RUN npx sequelize-cli db:migrate

RUN npx sequelize-cli db:seed:all


CMD npm run api:setup 

