FROM node:22-alpine

WORKDIR /usr/src/app

# Run the application as a non-root user.

# Copy the rest of the source files into the image.
COPY . .

# Expose the port that the application listens on.
EXPOSE 3000

# Run the application.
CMD npm run api:setup && npm run api:start


