name: self-hosted

on:
  push:
    branches: [ "main" ]

env:
  DB_USERNAME: vintalie
  DB_PASSWORD: 764066*
  DB_DATABASE: maresia
  DB_HOST: db
  DB_DIALECT: mysql
  DB_PORT: 3306

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Sync to github repository
        run: git pull
      - name: Build and push Docker image
        run: docker compose up -d --build


