name: self-hosted

on:
  push:
    branches: [ "main" ]

env:
  DB_USERNAME: vintalie
  DB_PASSWORD: 764066*
  DB_DATABASE: maresia
  DB_HOST: db
  DB_DIALECT: mysql
  DB_PORT: 3306

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        run: docker compose build
        run: docker compose up 
